### ISSUE TITLE
Rework server

### ISSUE THREAD

**Issue by ivysochyn** [ivysochyn/network-programming-project#3]
In the current state of server we're able to handle a single connection at the time. Instead we should operate on `set` of connected clients.

The task is to:
* Rework server to be able handle multiple connections at the same time
* Server should operate on all the connections (send a message for example)
* Server should be able to close connection with client that has no response

To be short, we should have server you can connect to, if client sends anything - respond with some message. In case client disconnected - remove connection from `set`.

**Comment by unbreaking-V** [comment]
To run the file, you need:
1. Enter the make command 
2. Run ./server in the first terminal window 
3. Run ./client in the second terminal window 

Expected result:
./server 

Test it works

**Comment by unbreaking-V** [comment]
To run the program, you need:
1. Enter the  command: make 
2. Run ./server in the first terminal window 
3. Run ./client in the second terminal window 

Expected result:
./server 

Test it works
